### PR TITLE
Add BlockLink component

### PR DESCRIPTION
**Pull request by merelinguist**

### CODE REVIEW

**Comment by lachlanjc** [comment]
This is fantastic, thank you @merelinguist!! Do you know why the theme snapshot has been deleted?

**Comment by merelinguist** [comment]
No idea, @lachlanjc! I just ran `yarn test -u`...

**Comment by lachlanjc** [comment]
Hmm. Can you revert the deletion and I'll merge + release this? Once I'm doing some more work on DS I'll investigate.

**Comment by lachlanjc** [comment]
Fabulous, really appreciate this 😌

**Pull request merged**
